export const CHANGE_PALETTE = 'CHANGE_PALETTE';
export const CHANGE_PALETTE_TEXT = 'CHANGE_PALETTE_TEXT';
export const CHANGE_PALETTE_ACTION = 'CHANGE_PALETTE_ACTION';
export const CHANGE_PALETTE_BACKGROUND = 'CHANGE_PALETTE_BACKGROUND';

export const TOGGLE_TYPOGRAPHY = 'TOGGLE_TYPOGRAPHY';
export const CHANGE_TYPOGRPAHY = 'CHANGE_TYPOGRAPHY';

export const FAB_INCREMENT = 'FAB_INCREMENT';
export const FAB_DECREMENT = 'FAB_DECREMENT';
