export const TOGGLE_COLOR = 'TOGGLE_COLOR';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const TOGGLE_TYPOGRAPHY = 'TOGGLE_TYPOGRAPHY';
export const CHANGE_TYPOGRPAHY = 'CHANGE_TYPOGRAPHY';

export const FAB_INCREMENT = 'FAB_INCREMENT';
export const FAB_DECREMENT = 'FAB_DECREMENT';
