export const TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME';
export const TOGGLE_LIGHT_THEME = 'TOGGLE_LIGHT_THEME';
export const TOGGLE_DEFAULT_THEME = 'TOGGLE_DEFAULT_THEME';
export const CHANGE_THEME = 'CHANGE_THEME';
